apiVersion: apps/v1
kind: Deployment
metadata:
  name: hectorh-internal-deployment
  labels:
    app: hectorh-internal
spec:
  selector:
    matchLabels:
      app: hectorh-internal
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      name: hectorh-internal
      labels:
        app: hectorh-internal
    spec:
      containers:
      - name: hectorh-internal-container
        image: hectorhernandezmarques/hectorh-internal-image:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: hectorh-internal-service
  labels:
    app: hectorh-internal
spec:
  ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
      name: hectorh-internal
  selector:
    app: hectorh-internal
  type: ClusterIP